#!/bin/sh

set -e

ISO_PUBLISHER="Subgraph"
ISO_APPLICATION="Subgraph OS"
ISO_VOLUME="Subgraph live $(date +%m%d%Y)"

lb config noauto \
  --clean \
  --distribution stretch \
  --debian-installer live \
  --linux-flavours "amd64" \
  --linux-packages "linux-image linux-headers" \
  --firmware-binary true \
  --firmware-chroot true \
  --source false \
  --apt-indices false \
  --apt-recommends false \
  --memtest memtest86+ \
  --iso-publisher "$ISO_PUBLISHER" \
  --iso-application "$ISO_APPLICATION" \
  --iso-volume "$ISO_VOLUME" \
  --archive-areas "main contrib non-free" \
  --initramfs "live-boot" \
  --bootappend-live "boot=live noconfig=sudo username=user user-fullname=User hostname=subgraph union=overlay quiet splash apparmor=1 security=apparmor" \
	"${@}"
